log:
  # 控制台日志参数
  enableConsole: true
  consoleJSONFormat: true
  consoleLevel: Debug
  # 文件日志参数
  enableFile: true
  fileJSONFormat: false
  fileLevel: Debug
  fileLocation: log/log.txt
  maxAge: 28 # 最大天数
  maxSize: 100 # 文件最大容量
  compress: true # 是否压缩

#web服务配置
webapi:
  uri: 0.0.0.0:8080

#数据库配置
mysqlnd:
  username: root
  password: 123
  host: 127.0.0.1
  port: 3306
  database: top_up
  history: ubox_his

#redis配置
redis:
  host: 127.0.0.1
  port: 6339
  password: 123456

#doplhinDB配置
dolphindb:
  host: 127.0.0.1 
  port: 8848
  username: admin
  password: 123456
  db: mydb

#redisubpub topic
topic:
  Request_command_channel: "Request/command/channel"
  Request_command_sysmgr: "Request/command/sysmgr"
  Request_command_dp: "Request/command/dp"
  Request_command_dolphindb: "Request/command/dolphindb"
  Request_command_fep: "Request/command/fep"
  Request_command_pointtable: "Request/command/pointtable"
  Request_command_rtu: "Request/command/rtu"
  Request_command_process: "Request/command/process"
  Response_watch_point: "Response/watch/point"
  Alarm_system_warning: "Alarm/system/warning"
  Alarm_system_error: "Alarm/system/error"
  Alarm_system_fatal: "Alarm/system/fatal"
  Response_show_message: "Response/show/message"
  Response_to_console: "Response/to/console"