log:
    enableConsole: true
    consoleJSONFormat: true
    consoleLevel: Debug
    enableFile: true
    fileJSONFormat: false
    fileLevel: Debug
    fileLocation: log/log.txt
    maxAge: 28
    maxSize: 100
    compress: true
webapi:
    uri: 0.0.0.0:8080
mysqlnd:
    username: root
    password: "123"
    host: 127.0.0.1
    port: "3306"
    database: top_up
    history: ubox_his
redis:
    host: 127.0.0.1
    port: 6339
    password: "123456"
dolphindb:
    host: 127.0.0.1
    port: 8848
    username: admin
    password: "123456"
    db: mydb
system:
    enable_prevent_losses: false
    enable_limit_same_channel: false
    enable_allow_same_number: true
    to_up_info_type: 0
    supplier_order_no_up: 1
    order_save_days: 30
    system_maintenance_time: ""
    notify_number: "123456"
    card_onsume_order: 0
    query_exclude_failure: false
    card_arvchine_days: 0
    card_check_repeat: true
