basePath: /api
host: 127.0.0.1:8080
info:
  contact:
    email: 17732235526@163.com
    name: API Support
    url: http://www.swagger.io/support
  description: this is a sample server celler server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - multipart/form-data
      description: 用户登录
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg":"登录成功","token":token,"code":200,"data":{}
          schema:
            type: json
        "404":
          description: 未找到此用户
        "500":
          description: 获取账号信息出错
      summary: 获取账号进行登录
swagger: "2.0"
